export type MockUser = {
  id: string
  name: string
  email: string
  emailVerified: boolean
  image: string | null
  createdAt: Date
  updatedAt: Date
  twoFactorEnabled: boolean | null
  username: string | null
  displayUsername: string | null
  role: string | null
  banned: boolean | null
  banReason: string | null
  banExpires: Date | null
}

export type UserStatus = "active" | "banned"

export function getUserStatus(user: MockUser): UserStatus {
  return user.banned ? "banned" : "active"
}

export const mockUsers: MockUser[] = [
  {
    id: "usr_01",
    name: "Alice Martin",
    email: "alice.martin@example.com",
    emailVerified: true,
    image: null,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2025-04-10"),
    twoFactorEnabled: true,
    username: "alice",
    displayUsername: "Alice",
    role: "admin",
    banned: false,
    banReason: null,
    banExpires: null,
  },
  {
    id: "usr_02",
    name: "Bruno Dupont",
    email: "bruno.dupont@example.com",
    emailVerified: true,
    image: null,
    createdAt: new Date("2024-03-22"),
    updatedAt: new Date("2025-05-01"),
    twoFactorEnabled: false,
    username: "bruno",
    displayUsername: "Bruno",
    role: "user",
    banned: false,
    banReason: null,
    banExpires: null,
  },
  {
    id: "usr_03",
    name: "Claire Bernard",
    email: "claire.bernard@example.com",
    emailVerified: false,
    image: null,
    createdAt: new Date("2024-06-08"),
    updatedAt: new Date("2025-03-18"),
    twoFactorEnabled: false,
    username: "claireb",
    displayUsername: "Claire",
    role: "user",
    banned: true,
    banReason: "Violation des conditions d'utilisation",
    banExpires: new Date("2025-12-31"),
  },
  {
    id: "usr_04",
    name: "David Leroy",
    email: "david.leroy@example.com",
    emailVerified: true,
    image: null,
    createdAt: new Date("2024-08-30"),
    updatedAt: new Date("2025-05-12"),
    twoFactorEnabled: true,
    username: "davidl",
    displayUsername: "David",
    role: "moderator",
    banned: false,
    banReason: null,
    banExpires: null,
  },
  {
    id: "usr_05",
    name: "Emma Petit",
    email: "emma.petit@example.com",
    emailVerified: true,
    image: null,
    createdAt: new Date("2024-11-02"),
    updatedAt: new Date("2025-04-28"),
    twoFactorEnabled: false,
    username: "emma",
    displayUsername: "Emma",
    role: "user",
    banned: false,
    banReason: null,
    banExpires: null,
  },
  {
    id: "usr_06",
    name: "François Moreau",
    email: "francois.moreau@example.com",
    emailVerified: true,
    image: null,
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-05-15"),
    twoFactorEnabled: false,
    username: "francois",
    displayUsername: "François",
    role: "user",
    banned: true,
    banReason: "Spam répété",
    banExpires: null,
  },
  {
    id: "usr_07",
    name: "Gabrielle Roux",
    email: "gabrielle.roux@example.com",
    emailVerified: true,
    image: null,
    createdAt: new Date("2025-02-14"),
    updatedAt: new Date("2025-05-08"),
    twoFactorEnabled: true,
    username: "gabrielle",
    displayUsername: "Gabrielle",
    role: "admin",
    banned: false,
    banReason: null,
    banExpires: null,
  },
  {
    id: "usr_08",
    name: "Hugo Simon",
    email: "hugo.simon@example.com",
    emailVerified: false,
    image: null,
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-05-10"),
    twoFactorEnabled: false,
    username: "hugo",
    displayUsername: "Hugo",
    role: "user",
    banned: false,
    banReason: null,
    banExpires: null,
  },
  {
    id: "usr_09",
    name: "Isabelle Laurent",
    email: "isabelle.laurent@example.com",
    emailVerified: true,
    image: null,
    createdAt: new Date("2025-03-20"),
    updatedAt: new Date("2025-05-14"),
    twoFactorEnabled: false,
    username: "isa",
    displayUsername: "Isabelle",
    role: "user",
    banned: false,
    banReason: null,
    banExpires: null,
  },
  {
    id: "usr_10",
    name: "Julien Michel",
    email: "julien.michel@example.com",
    emailVerified: true,
    image: null,
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-05-16"),
    twoFactorEnabled: true,
    username: "julien",
    displayUsername: "Julien",
    role: "moderator",
    banned: false,
    banReason: null,
    banExpires: null,
  },
  {
    id: "usr_11",
    name: "Karine Blanc",
    email: "karine.blanc@example.com",
    emailVerified: true,
    image: null,
    createdAt: new Date("2025-04-12"),
    updatedAt: new Date("2025-05-17"),
    twoFactorEnabled: false,
    username: "karine",
    displayUsername: "Karine",
    role: "user",
    banned: false,
    banReason: null,
    banExpires: null,
  },
  {
    id: "usr_12",
    name: "Lucas Girard",
    email: "lucas.girard@example.com",
    emailVerified: true,
    image: null,
    createdAt: new Date("2025-04-25"),
    updatedAt: new Date("2025-05-18"),
    twoFactorEnabled: false,
    username: "lucas",
    displayUsername: "Lucas",
    role: "user",
    banned: false,
    banReason: null,
    banExpires: null,
  },
]
